services:
  # postgres:
  #   image: postgres:15
  #   container_name: postgres_web_app_ts
  #   environment:
  #     POSTGRES_USER: studform_db_user
  #     POSTGRES_PASSWORD: studform_db_1488
  #     POSTGRES_DB: studform_db
  #   ports:
  #     - "5432:5432"
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready -U studform_db_user -d studform_db"]
  #     interval: 5s
  #     timeout: 5s
  #     retries: 5
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   networks:
  #     - shared
  backend:
    build:
      context: .
      dockerfile: ./applications/server/Dockerfile
    environment:
      DB_USER: studform_db_user
      DB_PASSWORD: studform_db_1488
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: studform_db
      PORT: 3000
      BOT_TOKEN: ${BOT_TOKEN}
      DIRECTUS_URL: http://directus:8055
    ports:
      - "3000:3000"
    networks:
      - shared
    restart: unless-stopped
  frontend:
    build:
      context: ./applications/web-app/
      dockerfile: ./Dockerfile
    ports:
      - "3001:3000"
    depends_on:
      - backend
    networks:
      - shared
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
    networks:
      - shared

volumes:
  postgres_data:
networks:
  shared:
    driver: bridge